### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by acabal** [SzymonSzott/joseph-conrad_nostromo#1]
- titlepage.svg is wrong dimensions. If you do `git pull` on the tools repo, you can use `create-draft` to create a dummy draft which will create a new titlepage image that has the correct dimensions.
- Remember to run build-images after updating the titlepage
- Epigraph should have Shakespeare in a `<cite>` tag, after `<p>` but within `<blockquote>`
- Add the following style to local.css for epigraphs:
    ````
    section[epub|type~="epigraph"]{
	    text-align: center;
    }
    
    section[epub|type~="epigraph"] blockquote{
	    display: inline-block;
	    margin: 5em auto;
	    text-align: left;
    }
    ````
- In colophon, add `<br/>` after IA link and after the line just before the Wikimedia link
- For each chapter, wrap the `<section epub:type="chapter">` element in the matching parent part section. For example, in `chapter-2-1.xhtml`, wrap the `<section>` with:  `<section id="part-2" epub:type="part">`. This is so that the files are recomposable using the `recompose-epub` tool. You can run it on your ebook and inspect the resulting DOM tree to ensure you have the matching sections correct.
- Part number HTML files need the part's subtitle in the `<title>` tag 
- The content.opf template changed since you started, to include some a11y boilerplate. Do a `git pull` on the tools repo, then compare the content.opf template to yours to get the right a11y metadata in there.

**Comment by SzymonSzott** [comment]
Thanks! Fixed in b7b99db534f4c45bb4443a79fbeda20442ef4fb0.
